### ISSUE TITLE
Wrong key index for signing transactions

### ISSUE THREAD

**Issue by aserdobintsev** [onflow/FRW-iOS#121]
### Describe the Bug

I have 6 keys connected with address and only the one non revoked key with index 5. But the app always uses key with index 0 to sign transactions and always fails.

In code key index is static 0 value.
https://github.com/Outblock/FRW-iOS/blob/develop/FRW/Services/Manager/WalletConnect/WalletConnectManager.swift#L280

### Expected experience

To sign transactions the app uses key with index that was imported to it.

### Steps To Reproduce

1. Find (or create) the address with several keys of weight 1000 connected with address.
2. Revoke key with index 0.
3. Import address to iOS app using private key of key with index other than 0.
4. Try to send FLOW(or any other) token, or stake.
5. 

### Environment

```markdown
- OS: iOS 16.7.1
- App version: 2.0.2(1)
- Device: iPhone 14 Pro
```

**Comment by Peppermint1020** [comment]
This issue already sloved in ios prod version 1.0.0(17).

**Comment by aserdobintsev** [comment]
I now have iOS Flow Ref app installed from the TestFlight - version 2.0.3(3).  And the app still uses wrong key to sign transactions.
Can't download 1.0.0(17) because the app is unavailable in the AppStore for my region.
