### ISSUE TITLE
UI Review

### ISSUE THREAD

**Issue by KK-UIUX** [onflow/FRW-iOS#152]
![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/f326d0e6-5be4-4f16-94d5-55de78727bc4)

![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/319cd7c5-65f1-48d3-802b-9b857e17516e)

![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/f2144c62-f481-4d4a-949e-75a7db50be29)

![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/b518a424-cda1-4ef3-99bc-e37151aed2e5)

![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/8846dc24-7347-4414-90a9-fb275a8772d6)

**Comment by JeffreyDoyle** [comment]
Hey @KK-UIUX @lmcmz -- I left some quick copy feedback on the Figma 😃  https://www.figma.com/file/mSr5uIApRJNrpkmN0YNuD6?type=design&node-id=18967-4530&mode=design#783675403

**Comment by Peppermint1020** [comment]
Not finish yet.
