### ISSUE TITLE
[BUG] swap ---- when input swap amount,  amount will change to 0 at the first time.

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#174]
### Describe the Bug

When use swap function, swap amount will change to 0 at the first time.
The bug is shown in the video attached below.

https://github.com/Outblock/FRW-iOS/assets/87978227/0f2b7e8d-c5ac-49ca-8515-4b82d7e62b4c

Check with Xiaoliu, the reason for the issue is the return from API. 
https://lilico.app/api/swap/v1/mainnet/estimate?inAmount=0.002&inToken=A.1654653399040a61.FlowToken&outToken=A.921ea449dffec68a.FlovatarDustToken
<img width="892" alt="image" src="https://github.com/Outblock/FRW-iOS/assets/87978227/412a2f57-87e4-41a7-8e3b-cfe903d3b3df">

### Expected experience

.

### Steps To Reproduce

Attached in above.

### Environment

```markdown
-ios 2.1.3(6)
```

**Comment by lmcmz** [comment]
We have disable swap within the app, close it for now
