### ISSUE TITLE
Instabug integration

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#20]

**Comment by Peppermint1020** [comment]
the function works fine. 

Step 1:

![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/2c9dfd21-9c9c-4c20-870e-a623b0389b39)

Step 2:


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/bc0705c0-753d-49a6-9187-5a9fab8eb584)

Step 3: navigate to email:


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/0b3a5986-413e-490e-a62d-e2d5e77d4557)
