### ISSUE TITLE
[Backup] Create Backup UI

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#22]

**Comment by zhouxl** [comment]
Backup UI

**Comment by Peppermint1020** [comment]
The test version is dev mode IOS version 2.0.4(2). The vision of test phone is IOS 17.1.2


There are some UI issue: 
1. The success icon need become green when user backup complete.
    The expect behaviour in UI design is:


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/ec8c81d9-551d-445f-9e28-ce392c1610eb)


   The actual behaviour we got is:


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/041f4057-0a53-4110-b690-9cf73fecc1d7)

**Comment by Peppermint1020** [comment]
This issue already solved in IOS prod version 2.0.4(7)
