### ISSUE TITLE
[BUG] Profile page --about page-- typo error -- discord & x

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#28]
### Describe the Bug

The word discord needs correcting on the about page on wallet iOS

### Expected experience

The word should be "discord", not "disocrd"
Also the word "twitter" need to to be change to "X"

### Steps To Reproduce

1. Go to profile page
2. Go to about page
3. scroll down to "contact us"
4. The link text should be "discord"
5. Also the link text "twitter" should be "X"

### Environment

```markdown
-IOS
```

**Comment by zhouxl** [comment]
done

**Comment by Peppermint1020** [comment]
Already fix the typo error in dev version 2.0.4(2)

![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/45268257-ab1e-415c-81ed-8792d6108ebc)


Future question: should we also change the icon for X or not?
