### ISSUE TITLE
[Backup] View recovery phrase in multi backup detail page

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#289]
https://www.figma.com/design/mSr5uIApRJNrpkmN0YNuD6/FLOW-REF-Mobile-Design-v2.0.0?node-id=18282-769&m=dev&t=vgk7IQm4CG5t726m-1

![Image](https://github.com/user-attachments/assets/1f874f43-3603-4a19-a928-775a55679cbf)

**Comment by Peppermint1020** [comment]
- [ ] ios
- [ ] Android

**Comment by Peppermint1020** [comment]
This feature already add in ios prod version 2.1.11(5)
