### ISSUE TITLE
[BUG] <register page --  no error message if username includes capital letter >

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#30]
### Describe the Bug
When I try to register new account, and use username with capital letter, the app will keep show checking and can not register for new account. I found this issue in flow ref wallet 2.0.4(1).
https://github.com/Outblock/FRW-iOS/assets/87978227/3219a931-9885-4da1-acd8-0d9d9bad0000

### Expected experience

The name with capital letter can be register successfully.
### Steps To Reproduce

1. Go to register page
2. input username

### Environment
ios 17.1.2
```markdown
- OS:
- Node:
- npm:
```

**Comment by zhouxl** [comment]
done
