### ISSUE TITLE
[Sync Process]UI Review

### ISSUE THREAD

**Issue by KK-UIUX** [onflow/FRW-iOS#33]
![Image](https://github.com/Outblock/FRW-iOS/assets/134983075/504255c1-185b-4f70-9919-1971f14e6c34)

**Comment by Peppermint1020** [comment]
The UI problem already solved in IOS version 2.0.4(5)

![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/4660da04-9758-4b4d-900f-fb541ad381f7)
