### ISSUE TITLE
[Feature]  Add Crescendo network support

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#38]
### Issue to be solved

There is a network for cadence 1.0 - crescendo

### Suggest A Solution

Update flow-swift SDK to 0.3.5
https://github.com/Outblock/flow-swift/commit/ac9b3f5f7653c5791057910257c2b416e5084d97

Replace sandboxnet with crescendo

Exploerer for crescendo: 
https://flow-view-source.vercel.app/

**Comment by Peppermint1020** [comment]
The add Crescendo network already achieved in IOS prod 2.0.4(4) beta version.
Now we can switch to Crescendo network in developer mode.
The following screenshot shows the detail.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/317c4e16-0208-47d8-a308-cd6a06cbb3f3)

After this action, in main page, we can see crescendo icon and address, and we can top up crescendo flow to this account.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/ac8568e7-24ae-4480-87c4-20f182219853)



![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/4c5ff8d4-9c95-498c-ae2b-2055de864d26)
