### ISSUE TITLE
[FEATURE] Update evm tx history API

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#417]
**Description:**

Currently, the EVM transaction history API uses the Cadence transaction history URL (https://www.flowscan.io/tx/[tx id]) for retrieving transaction details. We would like to update this for EVM accounts to use the Flow EVM explorer transaction URLs (https://evm.flowscan.io/tx/[tx id]), while keeping the existing URL format for Flow accounts unchanged.

**Proposed Changes:**

Update the transaction history API specifically for EVM accounts to use the Flow EVM explorer URL: https://evm.flowscan.io/tx/[tx id].
Do not change the transaction history API for Flow accounts; the URL format for Flow accounts should remain as https://www.flowscan.io/tx/[tx id].

**Expected Behavior:**

For EVM accounts, the transaction history API should return URLs in the format: https://evm.flowscan.io/tx/[tx id].
For Flow accounts, the transaction history API should continue returning URLs in the format: https://www.flowscan.io/tx/[tx id].
Both APIs should work independently for EVM and Flow accounts.

**Use Case:**

This update will ensure that EVM accounts are using the correct URL for viewing transaction details on the Flow EVM explorer, while Flow accounts continue using the legacy Cadence explorer URL.

Ref: https://github.com/Outblock/FRW/issues/58

**Comment by jeden** [comment]
@Peppermint1020 @zhouxl specs needed here too

**Comment by Peppermint1020** [comment]
> @Peppermint1020 @zhouxl specs needed here too

@jeden 

Hi Antonio,  

I’ve added the specs for this feature. Please have a look when you get a chance.  

Thanks!

**Comment by jeden** [comment]
Thanks @Peppermint1020.
In the code I see that there are three URLs for the transaction flow scan:

```
case .testnet:
    return URL(string: "https://testnet.flowscan.io/tx/\(hex)")
case .mainnet:
    return URL(string: "https://flowscan.io/tx/\(hex)")
case .previewnet:
    return URL(string: "https://previewnet.flowscan.io/tx/\(hex)")
```

Should I apply the same update to the other two (`testnet` and `previewnet`)? 
If yes, should they look like:

```
https://evm.testnet.flowscan.io/tx/[tx]
https://evm.previewnet.flowscan.io/tx/[tx]
```

or

```
https://testnet.evm.flowscan.io/tx/[tx]
https://previewnet.evm.flowscan.io/tx/[tx]
```

**Comment by Peppermint1020** [comment]
@jeden 
Don't worry about Previewnet. It was used for the Flow mainnet upgrade, and it has already been removed.

@caosbad cao
Could you provide API end point for testnet evm account there?

**Comment by caosbad** [comment]
https://test.lilico.app/api/evm/0xFACF71692421039876a5BB4F10EF7A439D8ef61E/transactions?network=testnet
https://test.lilico.app/api/evm/0x9F1026125E3fd8BccF47Ef5a23A9CB18fC660d6d/transfers?network=testnet

**Comment by jeden** [comment]
@caosbad @zzggo  I noticed there are some account detail URLs

```
string = "https://flowscan.org/account/\(self)"
string = "https://testnet.flowscan.org/account/\(self)"
string = "https://previewnet.flowscan.org/account/\(self)"
```

Should these be updated too? I see in [this commit](https://github.com/Outblock/FRW-Extension/commit/d08b3bec1d010d9a2fea43ee9041b2006d7afece#diff-bca2c9a4108741de6057225b4e71c1f0119a940f194e882f3777a640f40d4202R3140), `wallet.ts` file, line 3132, that base URLs are updated, so I presume the URL updates also applies to the `/account` paths.

_Update_: I've just noticed that their first-level domains are different (`.io` vs `.org`), so I presume they are handled differently, hence accounts should NOT be affected by this ticket.

**Comment by jeden** [comment]
@Peppermint1020 This is on Testflight version 2.3.0 build 51

**Comment by Peppermint1020** [comment]
@jeden 
The new evm tx history API is working fine in flow account,  but not working in EVM account. It seems we use cadence tx id in evm flowscan.

https://evm.flowscan.io/tx/ec9ba7115629b72e2c3ddc2d5588be952f5f1efb2ded1ee1b6edefb05f2350bb
https://github.com/user-attachments/assets/78f78b9d-8b6b-4919-9e96-0c05a3270164

**Comment by Peppermint1020** [comment]
This feature already add in ios dev version 2.3.4(72)
Process video:

https://github.com/user-attachments/assets/1e131590-6ed7-4c89-b460-788544d7bfca
