### ISSUE TITLE
[BUG] Failed to connect to flowty.io

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#451]
link: https://www.flowty.io/

**Comment by Peppermint1020** [comment]
Test on iOS prod version 2.2.9(8).
Our app can only connect with flowty by js.
Failed to connect with flowty by wc.

**Comment by Peppermint1020** [comment]
Test on iOS prod version 2.2.10(10).
Can connect to Flowty by scanning the QR code with WalletConnect.
But failed to connect by click "flow wallet mobile" in ios internal browser. The demo video is attached below.
https://github.com/user-attachments/assets/7fc4bc4d-b1c4-4957-a2f4-944e8e7ed11f

@zhouxl @lmcmz Please confirm this is error in our side or flowty side.

**Comment by zhouxl** [comment]
![Image](https://github.com/user-attachments/assets/227ca275-ddcc-44f4-be9a-0fa88a49b9cd)

**Comment by zhouxl** [comment]
https://github.com/user-attachments/assets/df9dbc96-da85-4336-a16d-7f51edad4f12

**Comment by JeffreyDoyle** [comment]
Investigation results:

- Flowty continues to fail to connect over wallet connect.
- Maybe Flowty is not using the latest version of FCL.

Next steps:

- We can report this issue to the Flowty team, to see if they can update their FCL version.
