### ISSUE TITLE
[FEATURE] Allow add EOA address in customised address book

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#460]
**Description:**

I would like to request a feature that allows users to add Externally Owned Account (EOA) addresses to their customized address book. Currently, when I try to add an EOA address, I receive an error stating, "This address is invalid."

**Current Behavior:**

When attempting to add an EOA address, the system returns an error message indicating that the address is invalid.

**Expected Behavior:**

Users should be able to successfully add valid EOA addresses to their customized address book without encountering error messages.

**Steps to Reproduce:**

(1) Navigate to the address book.
(2) Attempt to add a valid EOA address.
(3) Observe the error message stating, "This address is invalid."

**Comment by jeden** [comment]
![image](https://github.com/user-attachments/assets/c940158d-a448-4efd-9a30-afa96d31e433)
![image](https://github.com/user-attachments/assets/ac98dea0-2b1c-446e-9a4e-40550fe05b64)

**Comment by Peppermint1020** [comment]
The feature achieved in IOS prod version 2.2.11(7)
I can add EOA address successfully in customised address book.
![Image](https://github.com/user-attachments/assets/fe668ba9-dcbc-4801-85bb-58955c246cc7)
