### ISSUE TITLE
[FEATURE] Add custom token in EVM

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#465]

**Comment by Peppermint1020** [comment]
Tested on IOS prod version 2.2.10(4).

There are still two issues with the "Add Custom Token" feature: 

1. The displayed token amount for the custom token is incorrect; I do not have any USDC.e in my test account. 
2. After refreshing the page, the custom token disappears from my token list.
The demo video attached below.
https://github.com/user-attachments/assets/f5a30922-7e7a-421e-b7cc-c104453d93bc

**Comment by Peppermint1020** [comment]
Tested on IOS dev version 2.2.10(6).
Tested succeed in: 
(1) Add custom token 
(2) Delete custom token 
(3)Token in API but not in token list /custom token is not display in our app 
(4) send custom token to EOA

**Comment by Peppermint1020** [comment]
Confirm with Hao: 
 The "Add Custom Token" feature add the token to all profiles in the app.

Also need additional test: 
Custom token add in mainnet should not show in other network

**Comment by Peppermint1020** [comment]
Tested on IOS prod version 2.2.10(7).

Succeed in:
(1) Custom token add in mainnet should not show in other network
(2) Only token in testnet ERC20 token list can be add as testnet EVM custom token.
 Failed in: 
(1) The "Add Custom Token" feature add the token to all profiles in the app.

**Comment by Peppermint1020** [comment]
Tested on IOS prod version 2.2.10(8).
Succeed in:
(1) The "Add Custom Token" feature add the token to all profiles in the app.

@KK-UIUX 
Please review the UI part for this feature.
https://github.com/user-attachments/assets/121fb589-e13a-4583-9f03-9393170b7d8a

**Comment by Peppermint1020** [comment]
Tested on IOS prod version 2.2.10(9).
Succeed in:
(1) Add error toast when add custom token from wrong network.
https://github.com/user-attachments/assets/47b045b6-1c99-49fc-b859-619e45e458da

**Comment by KK-UIUX** [comment]
![Image](https://github.com/user-attachments/assets/04721f56-186a-4de9-9db2-811d62ab5896)

**Comment by zhouxl** [comment]
The font color is changed with the new UI specification

**Comment by Peppermint1020** [comment]
Discuss with Liu, waiting for new UI specification
