### ISSUE TITLE
[FEATURE] iOS CI Tool Integration - Xcode Cloud

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#483]
### Issue to be solved

Currently, there is no CI tool associated with this project. Perviously we are using bitrise, now we switch to Xcode cloud. :)

**Comment by jeden** [comment]
@lmcmz what were the previous rules for triggering a new build on Bitrise? PR merged to master?
Also, I would like to propose a git workflow and associated automated builds — what would be a good way to discuss this? I can post some notes here, or on a gdoc, or even better Notion, or I can discuss in a live meeting.
