### ISSUE TITLE
[FEATURE] Account storage alert

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#484]
### Issue to be solved

Background:
https://github.com/Outblock/FRW/issues/61

#### Get Storage and Available Balance Info

Our script API returns `getAccountInfo` cadence, which allow wallet to get the storage info under an account.
```swift
access(all) struct Result {
  access(all) let address: Address
  access(all) let balance: UFix64
  access(all) let availableBalance: UFix64
  access(all) let storageUsed: UInt64
  access(all) let storageCapacity: UInt64
  access(all) let storageFlow: UFix64,
}
```
If `storageCapacity - storageUsed < 10000` then it's insufficient storage

#### Notification
Currently, we use firebase remote config to control the notification messages. It use `news` at the moment.
For insufficient storage alert, we gonna add a new condition flag `insufficientStorage`, which user reach storage limit. 

#### Onchain Interaction
Any onchain Interaction, wallet need do a async check whether the storage is sufficient or not.

If it's send Flow Token or move action ( move fee ), the balance will be affected we need take count of the sending or move fee balance.  ( availableBalance - sent amount ) < 0.001
Other onchain Interaction, we only do the availableBalance check.

Following is the list of storage warning in action button:

1. Move token
2. Move NFT
3. Send Token
4. Send NFT
5. Sign Transaction on browser
6. Sign Transaction on WalletConnect

#### Transaction Listener
Every transaction submitted to the chain, the wallet will listen the callback. So when there is `storageCapacityExceeded`.
we need show an global alert telling user that the last transaction was failing due to storage.

#### Storage Usage Card
Storage info card need to be displayed only under FLOW token detail page.

Figma: 
https://www.figma.com/design/mSr5uIApRJNrpkmN0YNuD6/FLOW-REF-Mobile-Design-v2.0.0?node-id=35558-33202&t=eegpA2haFKcXcypT-1

**Comment by jeden** [comment]
@lmcmz where does this `10,000` value come from?

> If storageCapacity - storageUsed < 10,000 then it's insufficient storage

If `1 FLOW = 100MB`, then `0.001 FLOW = 0.1MB = 100KB = 102,400 bytes`. Unless that's an arbitrary value, or calculated in some other way that I am not aware of. Could you clarify?

**Comment by lmcmz** [comment]
Yes, you are right. Base on the average storage will use per transaction.

**Comment by jeden** [comment]
So you mean it's an arbitrary value not depending from total and used storage, right?

What if I have to do the same calc with an additional amount (to check if the stoage is insufficient after the transaction). 
The way I was calculating that is `accountInfo.availableBalance.doubleValue - amount < 0.001`, but not sure how to translate that in storage terms.

**Comment by lmcmz** [comment]
Yeah, it's very average presumption, it's `10KB = 10000 Bytes = 0.0001 FLOW`.  
Your equation looks right to me.

Just a reminder, if it's move action between EVM account and flow account, there is an 0.001 fixed fee. 

So it will become `accountInfo.availableBalance - amount - 0.001 < 0.001`

**Comment by Peppermint1020** [comment]
Test scenario:
Move operations

- [x] Move FLOW from the homepage.
- [x] Move other fungible tokens (FT) from the homepage. 
- [x] Move NFTs from the homepage.
- [x] Move FLOW from the FLOW token detail page.
- [ ] Move other fungible tokens (FT) from the token detail page.
- [x] Move NFTs from the NFT detail page.

Send Actions

- [x] Send FLOW from the homepage.
- [x] Send other fungible tokens (FT) from the homepage.
- [x] Send FLOW from the FLOW token detail page.
- [x] Send other fungible tokens (FT) from the token detail page.
- [x] Send NFTs from the NFT detail page.

Issues:
(1) The "Move" button on the other ft detail page is currently hidden, making it impossible to test this functionality.
![Image](https://github.com/user-attachments/assets/018771ef-066d-41e2-9733-bc5137893a0f)

(2) If send/move other fts/nft with no gas fee and move fee, the alert shouldn't pop up.

(3)The text content is missing for storage alert popup bottom button.
![Image](https://github.com/user-attachments/assets/5bc596a6-6c03-4da2-8f32-327e039db103)

(4) When move max amount flow token from main account, still remain 0.002 flow token which  is more than storage needs.
https://github.com/user-attachments/assets/54c79bec-d1bd-40fa-be77-afb7a721ebc8

Improvement:
(1) No alert for error 1101,Face this issue when move NFT from flow account to evm account with 0.001 flow token balance: https://www.flowscan.io/tx/8e4633c1b18874623c92a11c3e73f9f79aa1c72d34aece624e69a067587a461e

**Comment by jeden** [comment]
@Peppermint1020 I moved this back to ready for review, for more accurate testing it's better to work on a release built from the develop branch — the TestFlight version I sent you was built from the feature branch.

**Comment by jeden** [comment]
@Peppermint1020 approved, build in progress, check 2.2.10 (34), it should appear in about 30 mins

**Comment by Peppermint1020** [comment]
**Tested on iOS dev version 2.2.10(34)**
 

- [x] The "Move" button fixed other ft detail page.
- [x] The text content is missing for storage alert popup bottom button.
![Image](https://github.com/user-attachments/assets/ae6b55b1-990f-4369-b3fa-20abf6781ae9)
- [ ]  Create individual issue ticket for this problem and sign to Liu.When move max amount flow token from main account, still remain 0.002 flow token which is more than storage needs.
        https://github.com/Outblock/FRW-iOS/issues/618 
- [ ]  Create individual issue ticket for this problem: No alert for error 1101,Face this issue when move NFT from flow account to evm account with 0.001 flow token balance

**Issues:** 
- [ ] If send/move other fts/nft with no gas fee and move fee[when turn on free gas fee button], the alert shouldn't pop up.
(1) when send other fts from flow account to another flow account
(2)  when send nfts from flow account to another flow account
(3) when send/move other fts from flow account to child account
(4) when send/move  nfts from flow account to child account

@jeden Please have a look for last issue.

**Comment by jeden** [comment]
> * [ ]  If send/move other fts/nft with no gas fee and move fee[when turn on free gas fee button], the alert shouldn't pop up.
>   (1) when send other fts from flow account to another flow account
>   (2)  when send nfts from flow account to another flow account
>   (3) when send/move other fts from flow account to child account
>   (4) when send/move  nfts from flow account to child account
> 
> @jeden Please have a look for last issue.

@Peppermint1020 /cc @lmcmz  The alert is displayed when error `storageCapacityExceeded` (code 1103) is returned. I think this should be handled elsewhere by the entity returning this error. I could probably add more checks, but those should be repeated on the other platforms, so for uniformity/consistency it's better to handle that at the source.

**Comment by jeden** [comment]
@Peppermint1020 ready for QA, build 2.3.0 (40) https://testflight.apple.com/v1/app/6478996758?build=156642439

**Comment by Peppermint1020** [comment]
Waiting for new Design from KK
