### ISSUE TITLE
[Bug] Fix in app browser security issue

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#485]

**Comment by Peppermint1020** [comment]
Tested successfully on ios prod internal test version 2.2.10(5).

Update: 
Confirm with Hao. Need wait for new build, will test later.

**Comment by Peppermint1020** [comment]
Test successfully on iOS Prod version 2.2.10(6).

(1) Now the webview reading the actual url and displayed to the user.
(2) Succeed connect with Flow port and Flow rewards.

The demo video attached below.
https://github.com/user-attachments/assets/f01cab55-2368-4c7c-8ee0-3b35302f2bdc
