### ISSUE TITLE
[IMPROVEMENT]  Hide arrow button if token lacks external link

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#498]
**Description:** 
Currently, the arrow button is visible even when a token lacks an external link, leading to potential user confusion. The arrow button should only be shown if the token includes an external link. If there is no external link, the arrow button should be hidden.

**Expected Behavior:**

If a token contains an external link, the arrow button should appear.
If a token does not have an external link, the arrow button should be hidden.

**Steps to Reproduce:**

(1) choose a token from homepage.
(2) click the arrow icon.
![Image](https://github.com/user-attachments/assets/1fbeecf9-e62d-4975-9815-3ebe78fd5151)

**Acceptance Criteria:**

 

- [ ] Arrow button is only displayed when a token includes an external link.

 

- [ ] Arrow button is hidden when no external link is associated with the token.

**Comment by jeden** [comment]
![image](https://github.com/user-attachments/assets/6b5e10fa-0f88-4eb7-8dc3-35732daabafd)
![image](https://github.com/user-attachments/assets/cf972a1a-2ad8-4736-9150-b90887005881)

**Comment by Peppermint1020** [comment]
Discuss with Hao:

Most of token's website field is empty
If it's empty, we override to flowscan url
The exception is flow token on evm, since it's native token. It should hard coded as https://flow.com/

Wait Cao update those url on the token list.

**Comment by caosbad** [comment]
https://github.com/orgs/Outblock/projects/2/views/20?pane=issue&itemId=89269950&issue=Outblock%7CFRW-Server%7C194

https://github.com/Outblock/token-list-jsons/commit/44a38c9f2336c7c8eee4a4b5c992ead95aff34cf Commit here

**Comment by jeden** [comment]
@Peppermint1020 tested, and to me, it looks good. At standup, I think someone said URLs should be opened in the internal browser, but they are going to the external browser — is that ok?

**Comment by Peppermint1020** [comment]
@jeden Yes, it is OK to go to external browser.
The current issue is we also need to token in EVM account to flowscan evm URL.
![Image](https://github.com/user-attachments/assets/c349ba9c-d259-4c16-8349-0b5d3c624810)

**Comment by jeden** [comment]
@Peppermint1020 I can see the data in the config file, but for some reason the website disappears in the app. I'm debugging this issue, but probably I won't be able to fix it by today

**Comment by Peppermint1020** [comment]
This feature improvement already passed all tests. We can add this feature in next release bulid.
