### ISSUE TITLE
[BUG] IOS restore and backup issues

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#56]
### Describe the Bug

There are issues we got from 19/01/2024 test sessions. The test version is v 2.0.4(4). And my test phone is IOS 17.1.2.

The issues are listed below.
1. Transaction history request failed. When in token page click transaction, it not shown fail alert.
![IMG_3508](https://github.com/Outblock/FRW-iOS/assets/87978227/0ede2b80-41a0-4b70-aef4-9518d9a59324)
2. When create a new account, even address is invalid, and not go through all backup steps, still show google drive backup and cannot revoked. Also in same time, public keys not include google drive.

https://github.com/Outblock/FRW-iOS/assets/87978227/aaa2d2a1-66b2-4333-a381-75a9db35d1f3

![IMG_3513](https://github.com/Outblock/FRW-iOS/assets/87978227/2aff1278-783e-45a6-948a-ff17da50e2c7)

3. The account have two google drive backup.
![IMG_3515](https://github.com/Outblock/FRW-iOS/assets/87978227/60d0dad1-5e5e-4386-af3a-4ea683604e8d)

### Expected experience

1. One account can only have one google drive backup, iCloud backup and phrase backup.
2. Only valid address can be backup.

### Steps To Reproduce

In video above.

### Environment

```markdown
-IOS: 17.1.2
```

**Comment by zhouxl** [comment]
done

**Comment by Peppermint1020** [comment]
The three issues are solved in IOS dev version 2.0.4(14).
1. Now, we can view transaction history on transaction page.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/ac30bb49-6a2e-445a-8208-4608120944f9)


2. For the second issue, we add loading page to wait for creating account address.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/9a6e64e9-6b09-48f0-80f1-3678ffdf1d3e)


3. This issue already solved in testnet, but not in mainnet. Han will figure out it.
