### ISSUE TITLE
[Feature] Upgrade WC SDK to reown

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#578]

**Comment by Peppermint1020** [comment]
Test info:
Just make sure all existing WC behaviors are working correctly for both VM, which including
(1) Scan QRCode from desktop app including flow port and rainbow kit, and able to sign and connect
(2) Open dAPP in app browser, also able to connect and sign tx with WC
(3) Open dApp from mobile native browser, when select flow wallet mobile, we are able to connect and sign

**Comment by Peppermint1020** [comment]
Passed above tests
