### ISSUE TITLE
[FEATURE] Add backup flow after account creation

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#589]
# Issue to be solved

When a user creates a new profile in Flow Wallet mobile, after the profile is created, we must immediately prompt the user to optionally back up their account. This prompt must send the user down two paths, either to our existing backup view, or to the wallet dashboard.

The prompt can contain copy such as (suggestion): "Congratulations! Your Flow account is now ready. To best secure your account, you can backup your account now. " with buttons: "Back up" or "Maybe Later".

# Resource
https://www.figma.com/design/mSr5uIApRJNrpkmN0YNuD6/FLOW-REF-Mobile-Design-v2.0.0?node-id=25065-11991&t=3nqDGAO4U00gbe77-1

![Image](https://github.com/user-attachments/assets/3550740c-9c58-4692-b73b-a413ffe16d5a)

**Comment by jeden** [comment]
@Peppermint1020 @lmcmz The rest of the account creation flow has the title starting by lowercase (in this screen, "let's get started") — I presume that this screen is based on a slightly new design, but for consistency with the current flow I am using lowercase.

**Comment by jeden** [comment]
@Peppermint1020 This is on Testflight version 2.3.0 build 51

**Comment by Peppermint1020** [comment]
Tested on  version 2.3.0 build 51.
This feature already added.
![Image](https://github.com/user-attachments/assets/b5766856-1aa8-4ada-89fe-0062988765c8)
