### ISSUE TITLE
[BUG] Text content missing in verify password page

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#606]
**Description:**
The Verify Pin page is missing text content in top of the page. Also the arrow in top of page is not working.
![Image](https://github.com/user-attachments/assets/c15372d8-96eb-4d63-abab-446296f8e311)

**Steps to Reproduce:**

(1)Navigate to a feature or flow that requires pin verification. [multi- backup]
(2)Observe the Verify Pin page.

**Expected Behavior:**
(1)The Verify Password page should include clear text title.
(2)When click arrow icon, lead user back to previous page.

**Actual Behavior**:

(1)The page is missing title text.
(2) No response, when click arrow icon

**Environment:**

Version: prod 2.2.11(7)

**Comment by zhouxl** [comment]
Dev 2.3.1 (1)

**Comment by Peppermint1020** [comment]
Tested on iOS prod version 2.3.1(11)
 The text content bug already been fixed.
![Image](https://github.com/user-attachments/assets/fd3ef783-fd91-4516-b9c2-2ddfe70cdcbe)
