### ISSUE TITLE
[IMPROVEMENT] Storage alert---Add Alert for Error 1101 When Moving NFT

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#619]
**Description**
There is currently no alert displayed for Error 1101, which occurs when attempting to move an NFT from a Flow account to an EVM account with only a 0.001 FLOW token balance. This lack of feedback leaves users unaware of why the transaction fails, leading to confusion and frustration.
https://www.flowscan.io/tx/8e4633c1b18874623c92a11c3e73f9f79aa1c72d34aece624e69a067587a461e

**Steps to Reproduce**
(1)Ensure the Flow account balance is at 0.001 FLOW.
(2)Attempt to move an NFT from the Flow account to an EVM account.
(3)Observe the lack of error alerts when the transaction fails with Error 1101.

**Expected Behavior**
An alert should be displayed when Error 1101 occurs, informing the user about insufficient balance for the operation and the minimum required balance.

**Actual Behavior**
No alert is displayed, and users are left to troubleshoot the issue without clear guidance.

Environment
Platform: iOS dev 2.2.10(34)

**Comment by jeden** [comment]
Closing this ticket as we need a proper ad-hoc error to describe the error condition that should trigger the alert.
