### ISSUE TITLE
[FEATURE] Add  feature toggle for storage alert feature

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#631]
Relates to:
- [#450](https://github.com/Outblock/FRW-Android/issues/450) (android)
- [#248](https://github.com/Outblock/FRW-Extension/issues/248) (extension)

**Comment by jeden** [comment]
@Peppermint1020 ready for review, build https://testflight.apple.com/v1/app/6478996758?build=156653565.

**Comment by jeden** [comment]
@Peppermint1020 updated build https://testflight.apple.com/v1/app/6478996758?build=156663130

**Comment by Peppermint1020** [comment]
@lmcmz Could you check this feature? I am not sure how could I test this one
