### ISSUE TITLE
[IMPROVEMENT]Upgrade storage alert feature to New UI design

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#653]
Storage Alert is ready. Storage Limit Error attached below:
https://www.figma.com/design/mSr5uIApRJNrpkmN0YNuD6/Flow-Wallet-Mobile-Design-v2.0.0?node-id=35558-33202&t=gHsyWuGmENMgTzUD-1
Please upgrade storage alert feature to New UI design

**Comment by jeden** [comment]
Since it wasn't clear when the warning popups should be displayed, I asked Jeff, and the answer is:

> The warning popups are displayed when the user selects "learn more" on the small toasts, and the error popup is displayed if a transaction errors due to a storage limit error

**Comment by jeden** [comment]
@Peppermint1020 build no. 48 available on TestFlight

**Comment by Peppermint1020** [comment]
@jeden 
Tested on ios dev version 2.3.0(48)
DONE: (1) Each time a "no storage" error occurs, our app displays a "Storage Limit Error" message.
![Image](https://github.com/user-attachments/assets/d11decd6-c7ff-4988-b4cf-27041ab59594)
Not done yet:
(1)Users need to receive a notification if their main account's Flow token balance is less than 0.001 or their available storage is less than 10KB.
<img width="589" alt="Image" src="https://github.com/user-attachments/assets/a42eee1a-7def-4cf5-b473-6acf1dd3a722" />

**Comment by jeden** [comment]
> Not done yet:
> (1)Users need to receive a notification if their main account's Flow token balance is less than 0.001 or their available storage is less than 10KB.

@Peppermint1020 This is covered by https://github.com/Outblock/FRW-iOS/issues/564

**Comment by jeden** [comment]
@Peppermint1020 the insufficient storage notification not shown on the home screen is fixed as part of #564
