### ISSUE TITLE
update price Identifier from symbol to new file

### ISSUE THREAD

**Issue by Peppermint1020** [onflow/FRW-iOS#660]

**Comment by zhouxl** [comment]
See if the token corresponds to the same price as extension or Android

**Comment by Peppermint1020** [comment]
@zhouxl 
The price is different with extension 2.6.3.The price of FUSD is different.
<img width="404" alt="Image" src="https://github.com/user-attachments/assets/2ed4be5c-b4f5-4c27-bb17-fa0e6c169f52" />
![Image](https://github.com/user-attachments/assets/4ee6752f-6714-462b-b831-f0bb0f10c839)

**Comment by lmcmz** [comment]
It's the same price on API, maybe android and extension are wrong.
https://lilico.app/api/prices

**Comment by Peppermint1020** [comment]
cc: @jaymengxy  @zzggo Please check this issue.
Let's use the API response instead
The hardcode is out of date

- [x] Extension
- [x] Android
