### ISSUE TITLE
[BUG] crashed when delete wallet

### ISSUE THREAD

**Issue by zhouxl** [onflow/FRW-iOS#693]
In versions above iOS 18

**Comment by Harvey-joe** [comment]
Hello @zhouxl  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Peppermint1020** [comment]
This bug already fixed in ios dev version 2.3.2 （6）
