### ISSUE TITLE
Display EVM Address

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#79]

**Comment by Peppermint1020** [comment]
This feature already achieved in flow wallet ios dev version1.0.0(10).
The app display evm address in main page and sidebar.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/8f342b0d-712e-4309-a8b3-609b04bbbf03)



![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/6542f57a-d05c-4d7d-a348-207366f5df52)
