### ISSUE TITLE
Display EVM balance

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#80]

**Comment by Peppermint1020** [comment]
This feature already achieved in flow wallet ios dev version1.0.0(10).
The app display evm balance in main page and token page.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/819cfbd5-3c79-4395-b03a-e64d9517039c)
![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/3edbbd77-084b-4c9f-8eec-7cf30ccc20ff)
