### ISSUE TITLE
EVM Welcome Page

### ISSUE THREAD

**Issue by lmcmz** [onflow/FRW-iOS#89]

**Comment by Peppermint1020** [comment]
The evm welcome page already build in flow wallet ios dev version 1.0.0(10).
There are two issues need to be improve.
(1) The skip button background color in dark mode is different with UI design.
(2) There is no link linked with learn more button yet.


![Image](https://github.com/Outblock/FRW-iOS/assets/87978227/9f178387-6179-4a29-9ece-739e22c97503)

**Comment by Peppermint1020** [comment]
above issue already been solved。
